# Generated by Django 2.2 on 2021-07-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=100)),
                ('dt_created', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('no_bedrm', models.IntegerField()),
                ('no_bathrm', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img1', models.URLField()),
                ('img2', models.URLField()),
                ('img3', models.URLField()),
            ],
        ),
    ]
